version: '3.9'
services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports: ["2181:2181"]

  kafka:
    image: bitnami/kafka:3.7
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    ports: ["8123:8123", "9000:9000"]
    volumes:
      - ./../schema/sql/clickhouse/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  apicurio:
    image: quay.io/apicurio/apicurio-registry-mem:2.6.5.Final
    ports: ["8081:8080"]
    environment:
      - QUARKUS_HTTP_PORT=8080

  superset:
    image: apache/superset:3.0.2
    ports: ["8088:8088"]
    environment:
      - SUPERSET_SECRET_KEY=playtics
    depends_on: [clickhouse]

  otel-collector:
    image: otel/opentelemetry-collector:0.100.0
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml:ro
    command: ["--config", "/etc/otel-collector.yaml"]
    ports: ["4317:4317", "4318:4318"]
