slice_name: Experiment CR 24h by Country (fast)
viz_type: echarts_timeseries_line
params:
  datasource: fb222222-2222-4222-8222-222222222222
  viz_type: echarts_timeseries_line
  x_axis: exposure_date
  time_grain_sqla: P1D
  groupby:
    - country
  row_limit: 10
  metrics:
    - label: avg_cr_24h
      expressionType: SQL
      sqlExpression: avg(cr_24h)
  time_range: No filter
uuid: fb888888-8888-4888-8888-888888888888

