slice_name: Experiment CR 24h by Platform (fast)
viz_type: echarts_timeseries_line
params:
  datasource: fb222222-2222-4222-8222-222222222222
  viz_type: echarts_timeseries_line
  x_axis: exposure_date
  time_grain_sqla: P1D
  groupby:
    - platform
  metrics:
    - label: avg_cr_24h
      expressionType: SQL
      sqlExpression: avg(cr_24h)
  series_limit: 10
  series_limit_metric:
    label: sum_exposed
    expressionType: SQL
    sqlExpression: sum(exposed_users)
  order_desc: true
  emit_filter: true
  time_range: Last 90 days
uuid: fb777777-7777-4777-8777-777777777777
