slice_name: Experiment CR 24h by App Version (Top 10)
viz_type: echarts_timeseries_line
params:
  datasource: f2222222-2222-4222-8222-222222222222
  viz_type: echarts_timeseries_line
  x_axis: exposure_date
  time_grain_sqla: P1D
  groupby:
    - app_version
  row_limit: 10
  metrics:
    - label: avg_cr_24h
      expressionType: SQL
      sqlExpression: avg(cr_24h)
  time_range: No filter
uuid: f9999999-9999-4999-8999-999999999999
