{{- if .Values.hpa.gateway.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: playtics-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: playtics-gateway
  minReplicas: {{ .Values.hpa.gateway.minReplicas }}
  maxReplicas: {{ .Values.hpa.gateway.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.gateway.targetCPUUtilizationPercentage }}
{{- end }}
