name: Release

on:
  push:
    tags: [ 'v*' ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Superset bundle asset
        run: |
          cd bi/superset
          ./build_bundle.sh || true
      - name: Pick release notes file
        id: pick
        run: |
          VER="${GITHUB_REF_NAME}"
          if [ -f "docs/release-notes/${VER}.md" ]; then
            echo "body=docs/release-notes/${VER}.md" >> $GITHUB_OUTPUT
          else
            echo "body=CHANGELOG.md" >> $GITHUB_OUTPUT
          fi
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          body_path: ${{ steps.pick.outputs.body }}
          files: |
            bi/superset/playtics_dashboard_bundle.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
